name: deploy

on:
  push:
    branches-ignore:
      - template
  pull_request:
    branches-ignore:
      - template
jobs:
  Deployment:
    runs-on: ubuntu-latest
    env:
      RAILWAY_SERVICE_NAME: ${{ secrets.RAILWAY_SERVICE_NAME }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}  
    steps:
    - uses: actions/checkout@v2
    - name: become root
      run: sudo -s
    - name: initial installation
      run: apt-get update && apt-get install -y curl
    - name: more installation
      run: curl -fsSL https://railway.app/install.sh | sh
    - name: Deploy to Railway
      run: railway up --service=$RAILWAY_SERVICE_NAME -d
    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      with:
        initial_status: success
        token: ${{ github.token }}
        target_url: https://web-production-0ada.up.railway.app/
        environment: production
